add "สลิ่มก็รักจังประเทศจะพังแล้ว ...??"
narze/awesome-salim-quotes pull request #137
Opened 2022-10-15 14:43 UTC by topten1222

2022-10-15 15:25 UTC, Leomotors requested changes
อ่านชื่อ repo ใหม่ด้วยครับ อาเนียงง

![](https://media.tenor.com/xlR5vxCJh-0AAAAd/anya-end-of-the-world.gif)

2022-10-16 01:21 UTC, topten1222 commented
> อ่านชื่อ repo ใหม่ด้วยครับ อาเนียงง
> 
> ![](https://camo.githubusercontent.com/8689eb0b915e361a272c583425032d2a735bac8ca754664b861c188aea01ea43/68747470733a2f2f6d656469612e74656e6f722e636f6d2f786c52357678434a682d3041414141642f616e79612d656e642d6f662d7468652d776f726c642e676966) [ ![68747470733a2f2f6d656469612e74656e6f722e636f6d2f786c52357678434a682d3041414141642f616e79612d656e642d6f662d7468652d776f726c642e676966](https://camo.githubusercontent.com/8689eb0b915e361a272c583425032d2a735bac8ca754664b861c188aea01ea43/68747470733a2f2f6d656469612e74656e6f722e636f6d2f786c52357678434a682d3041414141642f616e79612d656e642d6f662d7468652d776f726c642e676966) ](https://camo.githubusercontent.com/8689eb0b915e361a272c583425032d2a735bac8ca754664b861c188aea01ea43/68747470733a2f2f6d656469612e74656e6f722e636f6d2f786c52357678434a682d3041414141642f616e79612d656e642d6f662d7468652d776f726c642e676966) [ ](https://camo.githubusercontent.com/8689eb0b915e361a272c583425032d2a735bac8ca754664b861c188aea01ea43/68747470733a2f2f6d656469612e74656e6f722e636f6d2f786c52357678434a682d3041414141642f616e79612d656e642d6f662d7468652d776f726c642e676966)

@Leomotors แก้แล้วครับ

2022-10-16 02:14 UTC, ronnapatp requested changes
ไม่ต้องมี # ข้างหลังก็ได้ครับ และก็ช่วยลบ ห ตรงบรรทัดที่ 697 ด้วย

2022-10-16 05:42 UTC, topten1222 commented
> ไม่ต้องมี # ข้างหลังก็ได้ครับ และก็ช่วยลบ ห ตรงบรรทัดที่ 697 ด้วย

@ronnapatp แก้ให้แล้วครับ ขอบคุณครับ

2022-10-16 08:38 UTC, ronnapatp approved these changes

2022-10-16 13:15 UTC, Leomotors approved these changes

2022-10-16 13:15 UTC, merged