feat: 🎸 payut rich man
narze/awesome-salim-quotes pull request #140
Opened 2022-10-16 19:11 UTC by sukritnak

2022-10-17 01:36 UTC, Leomotors approved these changes

2022-10-18 10:19 UTC, narze approved these changes

2022-10-18 10:21 UTC, narze requested changes
อยากให้เอาไปไว้ล่างสุดครับ เพราะ ID จะถูกเปลี่ยนเยอะถ้าเอาไปไว้ตรงกลาง

2022-10-22 07:47 UTC, narze commented
Please open new PR after the fix, closing this

2022-10-22 07:47 UTC, closed without merging